### ISSUE TITLE
流程管理页面访问不了

### ISSUE THREAD

**Issue by wonderfulMorty** [luoben147/warehouse#1]
流程管理页面访问不了，我的qq是：2110825316.您能加一下我告诉我怎么配置流程管理吗

**Comment by luoben147** [comment]
我改了sql没提交。现在已经更新了，你更新下sql文件就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Morty"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 下午4:26
收件人:&nbsp;"luoben147/warehouse"<warehouse@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[luoben147/warehouse] 流程管理页面访问不了 (#1)





 
流程管理页面访问不了，我的qq是：2110825316.您能加一下我告诉我怎么配置流程管理吗
